{% set python_min = '3.11' %}
{% set name = "descent" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/descent/archive/{{ version }}.tar.gz
  sha256: 6162ce370ce00022413c9cc41621ac29eead60f937eb3031a61744f77e5b680d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=80.0
    - setuptools_scm >=8
  run:
    - python >={{ python_min }}
    - smee-base >=0.10.0
    - pydantic
    - pyarrow
    - datasets
    - scipy
    - pytorch
  run_constrained:
    - openff-interchange-base >= 0.5.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - descent
  files:
    - test_version.py
  commands:
    - python test_basic_train.py

about:
  home: https://github.com/openforcefield/descent
  summary: 'Optimize classical force field parameters against reference data'
  description: |
    A framework that aims to offer a modern API for training classical force field parameters 
    (either from a traditional format such as SMIRNOFF or from some ML model) against reference 
    data using pytorch.
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE_3RD_PARTY
  doc_url: https://github.com/openforcefield/descent
  dev_url: https://github.com/openforcefield/descent

extra:
  recipe-maintainers:
    - SimonBoothroyd
    - j-wags
    - lilyminium
    - mattwthompson
    - Yoshanuikabundi
    - fjclark
