{% set name = "descent" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/descent/archive/{{ version }}.tar.gz
  sha256: d809bc8733dcc6628e637cabb651071fbadf989e6bd645e88ea494ef9cf3d7ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - versioningit
  run:
    - python >=3.10
    - smee >=0.5.2
    - pydantic >=2
    - pyarrow
    - scipy
    - pytorch
test:
  imports:
    - descent

about:
  home: https://github.com/SimonBoothroyd/descent
  summary: 'Optimize classical force field parameters against reference data'
  description: |
    A framework that aims to offer a modern API for training classical force field parameters 
    (either from a traditional format such as SMIRNOFF or from some ML model) against reference 
    data using pytorch.
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE_3RD_PARTY
  doc_url: https://github.com/SimonBoothroyd/descent
  dev_url: https://github.com/SimonBoothroyd/descent

extra:
  recipe-maintainers:
    - SimonBoothroyd
